[package]
name = "rayon-ingest"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
csv = "1.1.6"
rayon = "1.5.1"
flate2 = "1.0.20"
tar = "0.4.35"
